// Sport categories for athlete classification
export const SPORT_CATEGORIES = [
  { value: 'sepak_bola', label: 'Sepak Bola' },
  { value: 'futsal', label: 'Futsal' },
  { value: 'bulu_tangkis', label: 'Bulu Tangkis' },
  { value: 'tenis', label: 'Tenis' },
  { value: 'tenis_meja', label: 'Tenis Meja' },
  { value: 'basket', label: 'Basket' },
  { value: 'voli', label: 'Bola Voli' },
  { value: 'renang', label: 'Renang' },
  { value: 'atletik_sprint', label: 'Atletik - Sprint' },
  { value: 'atletik_lompat', label: 'Atletik - Lompat' },
  { value: 'atletik_lempar', label: 'Atletik - Lempar' },
  { value: 'atletik_jarak_menengah', label: 'Atletik - Jarak Menengah' },
  { value: 'atletik_jarak_jauh', label: 'Atletik - Jarak Jauh' },
  { value: 'angkat_besi', label: 'Angkat Besi' },
  { value: 'angkat_berat', label: 'Angkat Berat' },
  { value: 'tinju', label: 'Tinju' },
  { value: 'silat', label: 'Pencak Silat' },
  { value: 'taekwondo', label: 'Taekwondo' },
  { value: 'judo', label: 'Judo' },
  { value: 'karate', label: 'Karate' },
  { value: 'gulat', label: 'Gulat' },
  { value: 'senam', label: 'Senam' },
  { value: 'senam_ritmik', label: 'Senam Ritmik' },
  { value: 'sepeda', label: 'Balap Sepeda' },
  { value: 'sepeda_mtb', label: 'Sepeda MTB' },
  { value: 'sepeda_bmx', label: 'Sepeda BMX' },
  { value: 'panahan', label: 'Panahan' },
  { value: 'menembak', label: 'Menembak' },
  { value: 'dayung', label: 'Dayung' },
  { value: 'kano', label: 'Kano' },
  { value: 'panjat_tebing', label: 'Panjat Tebing' },
  { value: 'golf', label: 'Golf' },
  { value: 'hoki', label: 'Hoki' },
  { value: 'sepak_takraw', label: 'Sepak Takraw' },
  { value: 'baseball', label: 'Baseball' },
  { value: 'softball', label: 'Softball' },
  { value: 'rugby', label: 'Rugby' },
  { value: 'american_football', label: 'American Football' },
  { value: 'handball', label: 'Handball' },
  { value: 'polo_air', label: 'Polo Air' },
  { value: 'triathlon', label: 'Triathlon' },
  { value: 'duathlon', label: 'Duathlon' },
  { value: 'wushu', label: 'Wushu' },
  { value: 'muaythai', label: 'Muay Thai' },
  { value: 'mma', label: 'MMA' },
  { value: 'esports', label: 'E-Sports' },
  { value: 'catur', label: 'Catur' },
  { value: 'lainnya', label: 'Lainnya' },
] as const;

export type SportCategory = typeof SPORT_CATEGORIES[number]['value'];

export function getSportLabel(value: string | null | undefined): string {
  if (!value) return 'Belum ditentukan';
  const sport = SPORT_CATEGORIES.find(s => s.value === value);
  return sport?.label || value;
}

// Sport-specific biomotor priority recommendations
export const SPORT_BIOMOTOR_PRIORITY: Record<string, string[]> = {
  sepak_bola: ['daya_tahan', 'kecepatan', 'kelincahan', 'power', 'kekuatan'],
  futsal: ['kelincahan', 'kecepatan', 'daya_tahan', 'power', 'koordinasi'],
  bulu_tangkis: ['kelincahan', 'power', 'kecepatan', 'daya_tahan', 'fleksibilitas'],
  tenis: ['kelincahan', 'power', 'daya_tahan', 'kecepatan', 'fleksibilitas'],
  tenis_meja: ['kelincahan', 'kecepatan', 'koordinasi', 'power', 'fleksibilitas'],
  basket: ['power', 'kelincahan', 'daya_tahan', 'kecepatan', 'kekuatan'],
  voli: ['power', 'kelincahan', 'kekuatan', 'koordinasi', 'fleksibilitas'],
  renang: ['daya_tahan', 'kekuatan', 'power', 'fleksibilitas', 'koordinasi'],
  atletik_sprint: ['kecepatan', 'power', 'kekuatan', 'fleksibilitas', 'koordinasi'],
  atletik_lompat: ['power', 'kecepatan', 'kekuatan', 'fleksibilitas', 'koordinasi'],
  atletik_lempar: ['power', 'kekuatan', 'fleksibilitas', 'koordinasi', 'kecepatan'],
  atletik_jarak_menengah: ['daya_tahan', 'kecepatan', 'kekuatan', 'power', 'fleksibilitas'],
  atletik_jarak_jauh: ['daya_tahan', 'kekuatan', 'fleksibilitas', 'power', 'kecepatan'],
  angkat_besi: ['kekuatan', 'power', 'fleksibilitas', 'koordinasi', 'daya_tahan'],
  angkat_berat: ['kekuatan', 'power', 'fleksibilitas', 'daya_tahan', 'koordinasi'],
  tinju: ['daya_tahan', 'power', 'kecepatan', 'kelincahan', 'kekuatan'],
  silat: ['power', 'kelincahan', 'fleksibilitas', 'kecepatan', 'daya_tahan'],
  taekwondo: ['fleksibilitas', 'power', 'kecepatan', 'kelincahan', 'daya_tahan'],
  judo: ['kekuatan', 'power', 'daya_tahan', 'fleksibilitas', 'kelincahan'],
  karate: ['kecepatan', 'power', 'fleksibilitas', 'kelincahan', 'kekuatan'],
  gulat: ['kekuatan', 'daya_tahan', 'power', 'fleksibilitas', 'kelincahan'],
  senam: ['fleksibilitas', 'power', 'kekuatan', 'koordinasi', 'daya_tahan'],
  senam_ritmik: ['fleksibilitas', 'koordinasi', 'daya_tahan', 'power', 'kekuatan'],
  sepeda: ['daya_tahan', 'kekuatan', 'power', 'fleksibilitas', 'koordinasi'],
  sepeda_mtb: ['daya_tahan', 'power', 'kekuatan', 'kelincahan', 'koordinasi'],
  sepeda_bmx: ['power', 'kelincahan', 'kekuatan', 'koordinasi', 'kecepatan'],
  panahan: ['kekuatan', 'daya_tahan', 'koordinasi', 'fleksibilitas', 'power'],
  menembak: ['koordinasi', 'daya_tahan', 'kekuatan', 'fleksibilitas', 'power'],
  dayung: ['daya_tahan', 'kekuatan', 'power', 'fleksibilitas', 'koordinasi'],
  kano: ['daya_tahan', 'kekuatan', 'power', 'koordinasi', 'fleksibilitas'],
  panjat_tebing: ['kekuatan', 'daya_tahan', 'fleksibilitas', 'power', 'koordinasi'],
  golf: ['fleksibilitas', 'power', 'koordinasi', 'kekuatan', 'daya_tahan'],
  hoki: ['daya_tahan', 'kelincahan', 'kecepatan', 'power', 'kekuatan'],
  sepak_takraw: ['fleksibilitas', 'power', 'kelincahan', 'koordinasi', 'kecepatan'],
  baseball: ['power', 'kecepatan', 'koordinasi', 'kelincahan', 'kekuatan'],
  softball: ['power', 'kecepatan', 'koordinasi', 'kelincahan', 'kekuatan'],
  rugby: ['kekuatan', 'power', 'daya_tahan', 'kecepatan', 'kelincahan'],
  american_football: ['kekuatan', 'power', 'kecepatan', 'kelincahan', 'daya_tahan'],
  handball: ['power', 'kelincahan', 'daya_tahan', 'kecepatan', 'kekuatan'],
  polo_air: ['daya_tahan', 'kekuatan', 'power', 'kelincahan', 'fleksibilitas'],
  triathlon: ['daya_tahan', 'kekuatan', 'power', 'fleksibilitas', 'koordinasi'],
  duathlon: ['daya_tahan', 'kekuatan', 'power', 'fleksibilitas', 'kecepatan'],
  wushu: ['fleksibilitas', 'power', 'kecepatan', 'kelincahan', 'koordinasi'],
  muaythai: ['daya_tahan', 'power', 'kekuatan', 'fleksibilitas', 'kecepatan'],
  mma: ['daya_tahan', 'kekuatan', 'power', 'fleksibilitas', 'kelincahan'],
  esports: ['koordinasi', 'daya_tahan', 'fleksibilitas', 'kekuatan', 'power'],
  catur: ['daya_tahan', 'koordinasi', 'fleksibilitas', 'kekuatan', 'power'],
  lainnya: ['daya_tahan', 'kekuatan', 'kecepatan', 'power', 'fleksibilitas'],
};
